stages:
 - mavenbuild
 - maventest
 - autodeploy
 - frontendbuild
 - frontendtest
 
 
maven-build:
 stage: mavenbuild
 tags:
 - BACKEND
 script:
 - cd Spring
 - mvn package -B

maven-test:
 stage: maventest
 tags:
 - BACKEND
 script:
 - cd Spring
 - mvn test
 artifacts:
  paths:
   - Spring/target/*.jar

autoDeploy:
 stage: autodeploy
 tags:
 - BACKEND
 script:
 - cd Spring
 - mvn package
 - sudo mv target/*.jar /target/web-demo.jar
 - sudo systemctl stop systemd-web-demo
 - sudo systemctl start systemd-web-demo

frontend-build:
   stage: frontendbuild
   tags:
   - FRONTEND
   script:
   - pwd


 